### ISSUE TITLE
selecting centralIndia as region breaks deploy script

### ISSUE THREAD

**Issue by pkt1583** [Azure-Samples/apim-genai-gateway-toolkit#17]
If I select centralIndia as region the storage account name is too big. Azure storage account name has to be less then or equal to 24 characters. Suggest to remove aoaisim from https://github.com/Azure-Samples/apim-genai-gateway-toolkit/blob/main/infra/simulators/modules/simulatorBase.bicep#L24-L27. As the resources are anyways created in dedicated resource group

**Comment by prasann** [comment]
thanks for the contribution. the fix is merged now.
