### ISSUE TITLE
Override subscription key header name to enable easier SDK integration

### ISSUE THREAD

**Issue by lucashuet93** [Azure-Samples/apim-genai-gateway-toolkit#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> APIM subscription key should be sent in `api-key` header rather than `ocp-apim-subscription-key` to enable easier integration with SDKs

### Mention any other details that might be useful

> APIM automatically overrides this for you when adding the AOAI API manually in the portal

![image](https://github.com/Azure-Samples/apim-genai-gateway-toolkit/assets/16926044/04f1c075-c0dd-40e2-bfb3-7ffce85ef04d)

**Comment by stuartleeks** [comment]
Closed by #76, #77
