### ISSUE TITLE
Create architecture diagram

### ISSUE THREAD

**Issue by lucashuet93** [Azure-Samples/apim-genai-gateway-toolkit#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
- an architecture diagram should be added to the README that shows the entire set of services deployed to Azure

**Comment by prasann** [comment]
I have added a basic one, didn't close the issue on the other repo. we can work on more detailed if required.
